version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: booksdb
    environment:
      POSTGRES_USER: books_service
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: books
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U books_service -d books" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true